---
apiVersion: v1
kind: Service
metadata:
  name: wavefront-proxy
  labels:
    app: wavefront-proxy
  namespace: default
spec:
  ports:
    - name: wavefront
      port: 2878
      protocol: TCP
    - name: jaeger
      port: 9411
      protocol: TCP
  selector:
    app: wavefront-proxy