apiVersion: v1
kind: Service
metadata:
  name: onboarding
  labels:
    app: onboarding
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: onboarding
